version: '2'

services:
  nginx:
    image: nginx:1.10
    networks:
      - backtier
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3100:80"
    links:
      - upload1
      - upload2
      - upload3

  upload1:
    build: .
    image: hostview/upload
    volumes:
      - ./data:/data
    networks:
      - backtier
    environment:
      NODE_ENV: production
      sails_upload__datadir: /data

  upload2:
    build: .
    image: hostview/upload
    volumes:
      - ./data:/data
    networks:
      - backtier
    environment:
      NODE_ENV: production
      sails_upload__datadir: /data

  upload3:
    build: .
    image: hostview/upload
    volumes:
      - ./data:/data
    networks:
      - backtier
    environment:
      NODE_ENV: production
      sails_upload__datadir: /data

networks:
  backtier:
    driver: bridge